#===============================#
#   Misskey Web Configuration   #
#===============================#

# サーバーの管理者情報
# ex) "Your Name <youremail@example.com>"
maintainer: <string>

# 動かすことになるドメイン
host: "misskey.xyz"

# ユーザーのクライアントに関する設定をストアするDB(Mongo)の情報
mongo:
  uri: <string>
  options:
   user: <string>
   pass: <string>

# 2016年5月現在、APIがストリーミングを提供していないため直接APIサーバーのRedisに繋ぐ必要があるので、その情報
redis:
  host: <string>
  pass: <string>

# Web待ち受けポート
port:
  http: 80
  https: 443
  streaming: 3000

# TLS設定
https:
  enable: <boolean>
  # 以下証明書設定。 enable が false の場合は省略
  keyPath: <string>
  certPath: <string>

# APIサーバー設定
api:
  host: <string>
  port: <string>
  pass: <string>

# よく分からない
cookiePass: <string>

# セッションIDを保存するCookieのキー
sessionKey: "hmsk"

# よく分からない
sessionSecret: <string>

# reCAPTCHA設定
# SEE: https://www.google.com/recaptcha/intro/index.html
recaptcha:
  # サイトキー
  siteKey: <string>
  # シークレット
  secret: <string>

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ここから下は特に弄る必要は無いと思われます
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

bindIp: null

# テーマカラー
themeColor: "#ec6b43"

# サブドメイン設定
domains:
  admin: "admin"
  signup: "signup"
  signin: "login"
  signout: "logout"
  resources: "resources"
  about: "about"
  search: "search"
  help: "help"
  talk: "talk"
  forum: "forum"
  webApi: "himasaku"
  api: "api"
  developer: "dev"
  color: "color"
  share: "share"
  widgets: "widgets"
